Khalid test
cs4560-utah-sp24/test pull request #6
Opened 2024-03-19 19:41 UTC by KhalidTheeb

Base
 Test using multiple words

Soft Hyphens
 Tests need to use browser.set_parameters()
 Test >2 lines where some soft hyphens don't split

2024-03-29 21:12 UTC, pavpanchekha requested changes

2024-04-09 20:43 UTC, pavpanchekha requested changes

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter3-base-tests.md
> +	(13.0, 42.5, 'world', Font size=16 weight=normal slant=roman style=None)]
Whitespace is wrong here, tests will not pass. You need to either:
- Put the list on one line (don't do this)
- Change `NORMALIZE_WHITESPACE` (don't do this either)
- Use `wbemocks.print_list` (do this one)

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter3-exercise-soft-hyphens-tests.md
> +     (13.0, 61.0, 'split', Font size=16 weight=normal slant=roman style=None)]
This one is good.

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-base-tests.md
> +	 </html>
Our `print_tree` doesn't print close tags.

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-comments-tests.md
> +	>>> test_parse("This is normal text --> following text should also be normal")
Indentation issue

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-comments-tests.md
> +Test combinations "nested" cases
Add blank line between text & code blocks

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-comments-tests.md
> +         'This is normal text following text should also be normal'
I think this should be two text nodes:
```
<html>
  <body>
    'This is normal text'
    ' following ...'
```

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-comments-tests.md
> +         'This is normal text following text should also be normal'
Same

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-paragraphs-tests.md
>  ------------
Don't need this now

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-paragraphs-tests.md
> +	>>> test_parse("<p class='first-paragraph'>This has a class</p><p id='second-paragraph'>This has an ID</p>")
I don't think this exercise triggers the "nested `<p>` tags" thing literally at all, since these `<p>` tags aren't nested.

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-paragraphs-tests.md
> +	>>> test_parse("<div><p>Paragraph within a div</p><b>Bold text</b></div>")
Literally does not test the parent pointers

2024-04-09 20:43 UTC, pavpanchekha commented on tests/chapter4-exercise-scripts-tests.md
> +         </script>
No close tags, c'mon dude test this shit

2024-04-09 20:45 UTC, pavpanchekha requested changes

2024-04-09 20:45 UTC, pavpanchekha commented on tests/chapter4-base-tests.md
> +	 </html>
This isn't even the test! The issue is that some students, in `close_tag`, do:

```
def close_tag(self, node):
    # ...
    if node.tag == "/i":
      # ...
```

However, `node.tag` never includes the slash, they should write `node.tag == "i"`. If they make this mistake, the `</i>` behavior is never triggered and text never stops being italics. *That's* what we want to test for: not parsing, but whether we actually stop italicizing stuff when we reach a `</i>` tag.

2024-04-16 20:24 UTC, pavpanchekha requested changes

2024-04-16 20:24 UTC, pavpanchekha commented on ch03/base.md
> +    ...   wbemocks.print_list(wbemocks.normalize_display_list(dl))
??? Why define this function and then not call it?

2024-04-16 20:24 UTC, pavpanchekha commented on ch03/base.md
> +    ...   wbemocks.print_list(wbemocks.normalize_display_list(dl))
Also this breaks other tests.

2024-04-16 20:24 UTC, pavpanchekha commented on ch04/base.md
> +	     'B'
You have a lot of whitespace after the `'B'` and this test also fails.

2024-04-16 20:24 UTC, pavpanchekha commented on ch04/ex-comments.md
> +         'following text should also be normal'
Why is there no space at the beginning of "following"?

2024-04-16 20:24 UTC, pavpanchekha commented on ch04/ex-comments.md
> +         'following text should also be normal'
Same, missing space

2024-04-16 20:24 UTC, pavpanchekha commented on ch04/ex-paragraphs.md
> +    >>>test_parse("<p>This is <b>paragraph one</b> with <p>nested paragraph two</p></p>")
Lacks blank after `>>>`

2024-04-16 20:24 UTC, pavpanchekha commented on ch04/ex-scripts.md
> +         <script defer src="my-script.js">
```suggestion
         <script defer="" src="my-script.js">
```

2024-04-22 18:49 UTC, closed without merging

2024-04-22 18:50 UTC, KhalidTheeb commented
I opened two other pull requests in place of this outdated pull request.